### ISSUE TITLE
limit source information

### ISSUE THREAD

**Issue by jantman** [spulec/awslimits#2]
This project looks really cool - I looked at the screenshots in #1, and it looks quite interesting.

Before this gets too mature, though, could you please place a notice on any pages that show data derived from awslimitchecker (ideally linking back to the project), as required by the license? I'd be happy to open a PR for this if desired... my gut reaction would be a footer with something to the effect of "Limit values and usage calculated by [awslimitchecker](http://awslimitchecker.readthedocs.io/en/latest/) version <whatever version is installed>", but obviously the wording is up to you.

Thanks,
Jason

**Comment by spulec** [comment]
Thanks Jason! and thanks for the great project.

How does https://github.com/spulec/awslimits/pull/3 look?

**Comment by jantman** [comment]
Yeah, looks great. Thanks!

**Comment by spulec** [comment]
Closed with https://github.com/spulec/awslimits/pull/3
